jobs:
  # ---------- 1. Stripe Live US ----------
  - name: stripe_live
    schedule:
      type: integrated
      integrations:
        - blanching_broke    # Stripe first connector ID
    steps:
      - name: run models for stripe_live
        command: >
          dbt run --vars '{"stripe_database": "dbt-technical-training"}'
      - name: test models for stripe_live
        command: >
          dbt test --vars '{"stripe_database": "dbt-technical-training"}'

  # ---------- 2. Stripe Live EU ----------
  - name: stripe_live2
    schedule:
      type: integrated
      integrations:
        - blob_uncouple       # Stripe second connector ID
    steps:
      - name: run models for stripe_live2
        command: >
          dbt run --vars '{"stripe_database": "dbt-technical-training"}'
      - name: test models for stripe_live2
        command: >
          dbt test --vars '{"stripe_database": "dbt-technical-training"}'
