jobs:
  # ---------- 1. Stripe Live US ----------
  - name: stripe_live
    schedule:
      type: integrated
      integrations:
        - blanching_broke    # Stripe US connector ID
    steps:
      - name: run models for stripe_live
        command: >
          dbt run --vars '{"stripe_schema": "stripe_live", "stripe_database": "stripe_livedbt"}'
      - name: test models for stripe_live
        command: >
          dbt test --vars '{"stripe_schema": "stripe_live", "stripe_database": "stripe_livedbt"}'

  # ---------- 2. Stripe Live EU ----------
  - name: stripe_live2
    schedule:
      type: integrated
      integrations:
        - blob_uncouple       # Stripe EU connector ID
    steps:
      - name: run models for stripe_live2
        command: >
          dbt run --vars '{"stripe_schema": "stripe_live2", "stripe_database": "stripe_live2dbt"}'
      - name: test models for stripe_live2
        command: >
          dbt test --vars '{"stripe_schema": "stripe_live2", "stripe_database": "stripe_live2dbt"}'
